version: '3.7'
services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: kbs
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin

        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    db_data: