package cep;
import  com.ftn.sbnz.model.models.CarFailureEvent;
import  com.ftn.sbnz.model.models.Car;

rule "Check for Car Failure"
    salience 10
    when
        $car: Car($carId: carId, temperature > 100.0 || pritisak > 50.0 || oilLevel > 10)
    then
        System.out.println("Car failure happened to the car with id ");
        System.out.print($carId); 
        insert(new CarFailureEvent($carId));
end
