package cep1;

import com.ftn.sbnz.model.events.FinancialAid;
import com.ftn.sbnz.model.models.Student;
import com.ftn.sbnz.model.models.Notification;

global java.util.List notificationList;

rule "Notify Candidates about Financial Aid"
    agenda-group "new-aid"
    when
        $aid: FinancialAid( $aidInterest: requirement.researchInterest)
        $candidate: Student( $studentInterest: researchInterest)
        $match : String() from $studentInterest
        eval($aidInterest.contains($match))
    then
        Notification notification = new Notification($candidate.getId(), "Financial aid matching your research interests is available.", $aid.getId());
        insert(notification);
        notificationList.add(notification);
end

rule "Reminder for Financial Aid Deadline"
    agenda-group "aid-deadline"
    when
        $aid: FinancialAid($deadline: deadline, $aidInterest: requirement.researchInterest)
        $candidate: Student($studentInterest: researchInterest)
        eval($deadline.getTime() - System.currentTimeMillis() <= 24 * 60 * 60 * 1000)    
        $match : String() from $studentInterest
        eval($aidInterest.contains($match))
    then
        Notification notification = new Notification($candidate.getId(), "The deadline for financial aid application is approaching. Apply now!", $aid.getId());
        insert(notification);
        notificationList.add(notification);
end
