package cep;

import com.ftn.sbnz.model.events.FinancialAid;
import com.ftn.sbnz.model.models.Student;
import com.ftn.sbnz.model.models.Notification;


rule "Notify Candidates about Financial Aid"
    when
        $aid: FinancialAid()
        $candidate: Student(researchInterest containsAny $aid.requirement.researchInterest)
    then
        insert(new Notification($candidate.getId(), "Financial aid matching your research interests is available.", $aid.id));
end

rule "Reminder for Financial Aid Deadline"
    when
        $aid: FinancialAid($deadline: deadline)
        $candidate: Student(researchInterest containsAny $aid.requirement.researchInterest)
        eval($deadline.getTime() - System.currentTimeMillis() <= 24 * 60 * 60 * 1000)       // One day before deadline
    then
        insert(new Notification($candidate.getId(), "The deadline for financial aid application is approaching. Apply now!", $aid.id));
end
